name: roaster
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  google_fonts: ^5.0.0
  flutter_blue: ^0.8.0
  permission_handler: ^10.3.0
  flutter_localization: ^0.1.12
  intl: any
  intl_translation: ^0.18.2
  flutter_launcher_icons: ^0.13.1
  dio: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/favicon.jpg"
  web:
    image_path: "assets/icon/favicon.jpg"
    generate: true
  windows:
    image_path: "assets/icon/favicon.jpg"
    generate: true
  macos:
    image_path: "assets/icon/favicon.jpg"
    generate: true
